### ISSUE TITLE
Add filter to `PerformanceNavigationTiming` events list

### ISSUE THREAD

**Issue by delawski** [xwp/site-performance-tracker#1]
I think it would be beneficial to have a filter on the `PerformanceNavigationTiming` events array so that a user is able to alter the types of events that are being tracked. Currently only a three events are tracked by default:

* `domContentLoadedEventEnd`
* `domInteractive`
* `domComplete`

Here's a reference of event types that the `PerformanceNavigationTiming` exposes: https://developer.mozilla.org/en-US/docs/Web/API/PerformanceNavigationTiming

**Comment by mehigh** [comment]
Not relevant anymore.
