### ISSUE TITLE
Annotation-based hooking

### ISSUE THREAD

**Issue by szepeviktor** [xwp/site-performance-tracker#105]
Would you welcome a PR that removes
```php
add_action( 'wp_enqueue_scripts', array( $this, 'enqueue_scripts' ) );
```
and adds this?
```php
/**
 * Enqueue javascript to trigger web vitals tracking.
 *
 * @hook wp_enqueue_scripts
 */
public function enqueue_scripts() {
```

**Comment by kasparsd** [comment]
The annotation based hooks [used also in our plugin template](https://github.com/xwp/wp-foo-bar/blob/a6551d7525693ca6b6afd21600f6e670f32d5c79/php/class-plugin-base.php#L341-L377) are known to break on highly optimized environments that remove the comments during the PHP runtime. They also rely on reflection which is additional performance overhead, and are impossible to parse using the automated linters and tooling. Finally, they also feel like a bit of magic and additional abstraction that is not really necessary in the age of IDE autocomplete 😀

**Comment by szepeviktor** [comment]
🇱🇹 Anyways ... I listen to this rapper from _Kasparazeme_
https://youtu.be/FJBCye-EOdg?t=10
