### ISSUE TITLE
Make unit tests much better

### ISSUE THREAD

**Issue by szepeviktor** [xwp/site-performance-tracker#106]
Simple unit tests need no database.
https://github.com/Automattic/wordbless makes it possible!

**Comment by kasparsd** [comment]
Thanks for the suggestion @szepeviktor! Considering that we already have a working development environment and CI pipeline for the project that runs the unit tests on an actual WP instance with full DB access, we're not planning to remove or replace that functionality for now.

**Comment by szepeviktor** [comment]
All right.

WorDBless would make performance in `site-performance-tracker` a bit more shiny.
