### ISSUE TITLE
Disable custom dimensions for GA4

### ISSUE THREAD

**Issue by Tonnie-Exelero** [xwp/site-performance-tracker#115]
Currently, when GA4 Analytics is selected in the plugin settings, the three custom dimensions input fields are showing. With GA4, we don't need to set up the custom dimensions since they are already included. This is only needed when GA and GTM are selected. 

**Acceptance Criteria**

1. Do not show the following input fields in the settings UI when `GA4 Analytics` is selected under **Analytics Types**:
- Measurement Version
- Event Meta
- Event Debug

2. Ensure that when GA4 is selected, and inputs added, the settings can successfully save after removal of the custom dimensions input fields

**Comment by bharatpareek** [comment]
Working on this.

**Comment by bharatpareek** [comment]
There are some issues with PHPCS not working properly, figuring that out.
