### ISSUE TITLE
Add an opt-in support for TTI metric polyfill

### ISSUE THREAD

**Issue by delawski** [xwp/site-performance-tracker#2]
According to the [Google Developer Guides](https://developers.google.com/web/fundamentals/performance/user-centric-performance-metrics#tracking_tti) the only way to track Time To Interactive (TTI) is to use a [polyfill](https://github.com/GoogleChrome/tti-polyfill).

We should have a way to add the TTI metric along with adding the polyfill as an opt-in feature. I guess it could be another item in the `$entry_types` array. We currently filter this array using:

```php
apply_filters( 'site_performance_tracker_event_types', array $entry_types = [ 'paint', 'navigation', 'mark' ] );
```

**Comment by mehigh** [comment]
Not relevant anymore.
