### ISSUE TITLE
Add a UI

### ISSUE THREAD

**Issue by mehigh** [xwp/site-performance-tracker#30]
Selecting from a dropdown between the 3 analytics types
Fill in the specific analytics ID 
Depending on the selection, entering the numbers of the custom dimensions needed to send the debug data in.
Have an input to pick the ratio (0->1) of tracking for the web vitals.

Should contain a link to the web vitals report, and information surrounding the fact that the data range should only start for the dates when web vitals data is being sent.

**Comment by nandotess** [comment]
I can help with that. It's going to be a good opportunity to understand better this tool/plugin.

**Comment by mehigh** [comment]
Thinking at a point of offering backwards compatibility, we shouldn't sunset the manual configuration.. and rather when these things are filled in via code, to just turn the inputs the settings screen to disabled and have their data come from the theme options passed through.

**Comment by kasparsd** [comment]
We also need to consider multisite scenarios where we might want to configure things for all sites on the network.

Should existing `add_theme_supports()` calls override/disable any UI settings to ensure users don't accidentally override thing?
