### ISSUE TITLE
Add support to track web vitals in AMP

### ISSUE THREAD

**Issue by mehigh** [xwp/site-performance-tracker#31]
https://amp.dev/documentation/examples/advertising-analytics/tracking_core_web_vitals/

We are currently only tracking performance data outside of AMP. 

This will gather data (possibly all of it) from AMP, and requires a filter to toggle it on or off.

**Comment by delawski** [comment]
> 2\. When AMP page, enqueue AMP analytics library (local version?)

Note that AMP WP plugin [exposes a UI for configuring analytics](https://amp-wp.org/documentation/getting-started/analytics/). Maybe it could be used for tracking web vitals?

**Comment by mehigh** [comment]
@manuelRod 
1. setting shouldn't be present or visible unless the official AMP plug-in is active
2. I don't know if enqueueing the AMP analytics library is needed here, as we require some analytics as a prerequisite for the plug-in... so rather than adding it ourselves, hooking into appending the extra triggers might be the right way to do it here. 
3. follow the documentation. I haven't dived deep into that, and what we can do, mark it accordingly in the readme. (i.e. if only some work and some don't, that should be noted)
4. I don't get this question
5. Maybe we need to append some triggers according to what existing analytics library we have. Please do some research and apply this on a playground environment and gather some conclusions on what should be done to get it going before coming down with a development plan.

**Comment by delawski** [comment]
When using AMP WP plugin, even if you add the analytics code programmatically, the plugin should sanitize the output for AMP and enqueue all the required packages.

So it should be all about outputting a correct `<script type="application/json">…</script>` code when [`amp_is_request()`](https://amp-wp.org/reference/function/amp_is_request/) is `true`.

**Comment by mehigh** [comment]
We're not moving forward with these developments.
