### ISSUE TITLE
Not loading via Composer

### ISSUE THREAD

**Issue by mendezcode** [xwp/site-performance-tracker#43]
The tracker code is not loading when installed via composer, as suggested in the readme.

When installed via WP Admin » Plugins, things work as expected.

**Comment by kasparsd** [comment]
@mendezcode Can you please confirm how the plugin was installed via Composer?

Does the site use the Composer correctly -- does it load the `vendor/autoload.php` somewhere before plugins and themes such as `wp-config.php` for example?

The plugin relies on the PSR-4 autoload supplied by Composer for loading the class files per these rules here:

https://github.com/xwp/site-performance-tracker/blob/d5ea3282a1113919c2f607f5a6a569de36e1150f/composer.json#L50-L52

**Comment by mendezcode** [comment]
Hi @kasparsd

The plugin was installed as instructed by the readme:

```shell
composer require xwp/site-performance-tracker
```

I have tried on a new Local site, requiring both `/vendor/autoload.php` and `/vendor/composer/autoload_psr4.php` and was not able to see the tracker code rendered.

When installing and activating via WP Admin, things work as expected.
