### ISSUE TITLE
Bug: Interface in the UI

### ISSUE THREAD

**Issue by mehigh** [xwp/site-performance-tracker#56]
After the latest version (0.1.1+), the UI of the interface doesn't reflect the hard-coded values, showing the placeholders as if it wasn't already configured
![Screenshot 2022-03-07 at 14 31 41](https://user-images.githubusercontent.com/367593/157053660-eeebb2a4-208a-4066-9d1d-acce6ca90ea7.png)

**Comment by manuelRod** [comment]
@mehigh what do you mean with "doesn't reflect the hard-coded values".
When I do a fresh install, I get the placeholders.
When I set up settings and save, I get the saved settings.
Am I missing something?

**Comment by manuelRod** [comment]
Oh, I see, you mean when using add_theme_support to configure the plugin right?
But, how it should work ideally? Do **settings screen** overwrite **add_theme_support** or the opposite? 
From the documentation, I see settings should be set using  add_theme_support. Should Settings be read-only?

**Comment by mehigh** [comment]
Hi,

Historically we've only had add_theme_support for configuring the plug-in.
When these are present, we want the setting screen to reflect the configuration in code via readonly fields. 

The documentation could receive an update too... since we're now having a setting screen. 

We're having many websites with it setup in the code and want things not to be confusing when we're updating the plug-in for them.
