### ISSUE TITLE
Allow smaller Web Vitals Tracking Ratio 

### ISSUE THREAD

**Issue by manuelRod** [xwp/site-performance-tracker#80]
The minimum Web Vitals Tracking Ratio possible right now is 0.01.
There are client's sites with enough visits to pass the recommended 30k tracked events per day using "0.01", therefore we bump into :
![Screen Shot 2022-10-24 at 11 55 42 AM](https://user-images.githubusercontent.com/1736736/197500400-c2954a37-eb43-4fa5-a939-02c6086dc36d.png)

Allow smaller ratios.

**Comment by mehigh** [comment]
Let's support 0.001 as a ratio.
